# 修改语言文件
language: 'zh_cn'

conditions:
  java-script: 'js'
  permission: 'perm'
  placeholderapi: 'papi'
#  vault: 'money'
#  player-points: 'points'

# 修改物品功能内部注册名
functions:
  catch: 'catch'
  command: 'command'
  java-script: 'js'
  sound: 'sound'

# 修改物品源内部注册名
sources:
  easy-menu: 'self'
#  neige-items: 'ni'

# 自定义js工具类
# 想要彻底刷新工具只能重启服务器
# 插件自带papi 可以不用自己导入
script-tools:
#  PlaceholderAPI: "me.clip.placeholderapi.PlaceholderAPI"