name: EasyMenu
version: '${version}'
main: pers.soulflame.easymenu.EasyMenu
api-version: '1.13'
softdepend:
  - 'PlaceholderAPI'
  - 'NeigeItems'
  - 'Vault'
  - 'PlayerPoints'
authors: [ SoulFlame ]
description: 一款平平无奇的菜单插件
commands:
  easymenu:
    aliases:
      - 'em'
      - 'emenu'
      - 'easym'